name = "personal-website"
compatibility_date = "2024-01-01"
pages_build_output_dir = "./dist"

[build]
command = "npm run build"

[[pages.headers]]
for = "/*"
[pages.headers.values]
"X-Frame-Options" = "DENY"
"X-Content-Type-Options" = "nosniff"

[[pages.headers]]
for = "/admin"
[pages.headers.values]
"X-Frame-Options" = "SAMEORIGIN"

[[pages.headers]]
for = "*.yml"
[pages.headers.values]
"Content-Type" = "text/yaml; charset=utf-8"

[env.production]
vars = { SITE_URL = "https://personal-website.pages.dev" } 