name = "personal-website"
compatibility_date = "2024-01-01"
pages_build_output_dir = "./dist"

[build]
command = "npm run build"

[[pages.headers]]
for = "/*"
[pages.headers.values]
"X-Frame-Options" = "DENY"
"X-Content-Type-Options" = "nosniff"

[env.production]
vars = { SITE_URL = "https://madala.me" } 